spring:
  application:
    name: backend
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/backend?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:alksdnflkjqnwe}

test:
  test: qweasdf

springdoc:
  swagger-ui:
    path: /swagger-ui.html
